### ISSUE TITLE
Would it be better to make versionatt in SlowlyChangingDimension optional?

### ISSUE THREAD

**Issue by HereticSK** [chrthomsen/pygrametl#12]
`SlowlyChangingDimension` requires the underlying table have a version attribute `versionatt` of integer ytpe. I wonder if this requirement imposes some unnecesssary assumption on the structure of the underlying dimension table. If `versionatt` is not compulsory, would the `SlowlyChangingDimension` class be applicable to more table designs?

As far as I know, not every type 2 dimension requites a `versionatt`. If my understanding about the code is right, the role of  `versionatt` is to identify the newest version in the dimension. There are other ways to do this, such as a current sign attribute, or a `fromatt` being the exact date on which change happens. 

I am no expert in data warehouse. Is `versionatt` such a common design practice that should be explicitly implemented in the ETL framework? Would it be better to make `versionatt` optional?

**Comment by chrthomsen** [comment]
I agree that it would be nice if versionatt was optional. On the other hand, it will make other things more complex: The user would then always have to give values for at least some of the optional attributes. Otherwise there would be no way to find the newest version (if fromatt=None, toatt=None, versionatt=None, currentflag=None, we have no way to find the newest version unless we assume that the surrogate key values can be used for the ordering).

Ordering of NULLs is also done differently on different DBMSs which could cause problems if we use one of the dates for the ordering and the default value for the date is None/NULL.

So I'm in doubt if we should make versionatt optional or if it in the end is easier for the user to be forced to have a versionatt.

Best regards,
Christian Thomsen

**Comment by HereticSK** [comment]
In principle, I'd prefer to give users more freedom in table design, unless it is such a common and standard design practice that worth being hard coded. It seems a bit odd to me to have the table structure dependent on the ETL tool.

Is it a good idea to have something like `orderingatt` to let the user specify what to use for ordering, and then construct the lookup sql according to `orderingatt` or `currentflag`? That involves some trivial if-else statements, but should be simple enough not to have to change other parts. As for Ordering of NULLs, just raise a warning to remind the user that it is DBMS specific, if the default value of `orderingatt` is None/NULL? Or verbosely provide a boolean argument like `descending=True`?

If the above idea seems plausible, I'd be glad to submit a PR for further discussion. pygrametl is an ideal tool in my work. It is a great chance for me to contribute, learn more about data warehouse, and in the meantime get my job done. 😄

**Comment by chrthomsen** [comment]
I agree with you that it would be nice to give the users freedom. So it would be great if you could make a proposal for how that can be done!

It is important to ensure that existing programs don't change their behavior. Since a required attribute is turned into an optional attribute and some new optional attributes are added, that should be possible.
Please also consider `__lookupnewestlocally` which on some systems can do the sorting of versions a lot faster than the DBMS.

Thanks for your contributions!
