### ISSUE TITLE
fetchonetuple() method returning dict instead of tuple

### ISSUE THREAD

**Issue by etrevisani** [chrthomsen/pygrametl#18]
I'm trying to use TypeOneSlowlyChangingDimension and Dimension classes, passing a pymysql cursor object to create the ConnectionWrapper. As soon as my my Dimension or my SCD objects try to fetch the maximum id from the table, the execution returns the following error:
```
  File "C:\Program Files\Python35\lib\site-packages\pygrametl\tables.py", line 644, in __init__
    targetconnection=targetconnection)
  File "C:\Program Files\Python35\lib\site-packages\pygrametl\tables.py", line 449, in __init__
    targetconnection=targetconnection)
  File "C:\Program Files\Python35\lib\site-packages\pygrametl\tables.py", line 192, in __init__
    self.__maxid = self.targetconnection.fetchonetuple()[0]
KeyError: 0
```
As far as I could explore the bug, It's related to the fetchonetuple() method, which uses __cursor.fetchone() from the connector. At least for pymysql, the later returns a dict of type {'MAX(key)': MAX_INTEGER_ID}, while fetchonetuple() requires a tuple to pass along. The problem is extended to the Dimension class, which uses the method fetchonetuple() and try to call the position [0] from its suposed returning tuple, breaking the execution, as it receives a dict.

I had made a quick workaround on __init__.py that fixes that for pymysql:

```
    def fetchonetuple(self):
        """Return one result tuple."""
        if self.__cursor.description is None:
            return ()
        fetched_row=self.__cursor.fetchone()
        if fetched_row:
          key, values = fetched_row.popitem()
        else:
          key, values = None, None
        if values is None:
            return (None, None) * len(self.__cursor.description)
        else:
            return (key, values)
```

The changes above require the following changes on tables.py so they work properly:

`self.__maxid = self.targetconnection.fetchonetuple()[1]`

`keyvalue = self.targetconnection.fetchonetuple()[1]`

**Comment by chrthomsen** [comment]
Hello,

Thanks for reporting this. I don't think this problem is due to a bug in pygrametl.

It seems to me that you are using PyMySQL's DictCursor class instead of its Cursor class. I don't know how that happens - pygrametl just calls cursor() on the provided Connection object. Did you set the value of cursorclass for your PyMySQL Connection object? The default seems to be Cursor, not DictCursor. 

I'm afraid that the suggested workaround will lead to problems for other PEP249 implementations. As far as I know, the correct PEP249 behavior for Cursor's fetch* methods is to return sequences/tuples, not dicts. 

Best regards,
Christian Thomsen
