### ISSUE TITLE
The _before_lookup statement of BatchFactTable will cause batch loading to fail and reduce efficiency

### ISSUE THREAD

**Issue by qianxuanyon** [chrthomsen/pygrametl#26]
Hello

Whether the self.__insertnow() statement should not be executed in the _before_lookup method of BatchFactTable will cause batch loading to fail

**Comment by chrthomsen** [comment]
Hello,

We have to to call `__insertnow()` to make sure that all data is loaded before we try to do a `lookup`. Otherwise, the `lookup` would not find an inserted row if the row has not been loaded into the DB yet.

Please reopen and provide an illustrative example if you think there is something wrong in this.

Best regards,
Christian Thomsen
