### ISSUE TITLE
Duplicate key while double referencing dimensions

### ISSUE THREAD

**Issue by fromm1990** [chrthomsen/pygrametl#45]
Hi, I have an issue when a fact references a dimension more than once.

An example is attached, showing three distinct fuel types being mapped to only two distinct ids 
- 1 -> petrol
- 1 -> electricity
- 2 -> lpg

The attached example prints the id mappings rather than bulk loading them as I could not manage to  find an obvious way of bulkloading using sqlite. Further, I believe the printout shows the problem well enough.

[double_dim_ref_bug.zip](https://github.com/chrthomsen/pygrametl/files/8800649/double_dim_ref_bug.zip)

**Comment by chrthomsen** [comment]
Hi,

This is caused by these two lines in your example:
```
row["fuel_no"] = fuel_dim.ensure(row, namemapping={"fuel_name": "primary_fuel"})
row["secondary_fuel_no"] = fuel_dim.ensure(row, namemapping={"fuel_name": "secondary_fuel"})
```

The first time `ensure` is called, the key of fuel_dim is not present in the argument and pygrametl thus sets a value for it when the row is inserted into the underlying dimension table. That value is also returned and you add it to the row (`row["fuel_no"] = ...`). When `ensure` is called the second time, the key is thus present in the row and pygrametl will thus use the provided value. This is intended behavior.

In the concrete example, you can avoid the problem in different ways. You can swap the two lines calling `ensure` such that `row["fuel_no"]` is set by the last call. Alternatively, you can keep their current order and make pygrametl ignore the value for fuel_no by using the namemapping to map it to a name which **does not** exist in the row: `row["secondary_fuel_no"] = fuel_dim.ensure(row, namemapping={"fuel_name": "secondary_fuel", "fuel_no":"ignored"})`

Best regards,
Christian
